### ISSUE TITLE
Doesn't work on bootup

### ISSUE THREAD

**Issue by jonprocter** [zacharee/NachoNotch#12]
Hi! Not sure if this is actually a bug, or if it's intended but I need to manually tap the toggle twice to get it to work after a reboot. 

Using a Pixel 3 XL on the latest March update, along with the latest version of Nacho Notch. 

Thanks!

**Comment by ConlonNovak** [comment]
Having this issue on Pixel 9 Pro XL latest Android 14 update (AD1A.240905.004).

Expected functionality: app maintains functionality through reboots

Observed functionality: app does not automatically relaunch, despite toggle within app showing as "on"

Workaround: toggle app (once) to restore blacked out notch
