### ISSUE TITLE
Chrome (And maybe other apps?) notifications unclickable when Nacho notch is active

### ISSUE THREAD

**Issue by Rydako** [zacharee/NachoNotch#13]
Phone: Pixel 3 XL
Android Version: Android 10 Jan update 
Phone state: Unrooted, totally stock with locked bootloader
Nacho Notch version: 28/updated 10th October 2019 (According to playstore)

Noticed this occurring on the Dec update, but have completely reset (and reverted everything to stock) when I installed the Jan update.

Whenever chrome sends through a notification (Usually can x site send notifications OR can x site get your location) the buttons are not clickable until after you disable nacho notch from the QS tile.

Unsure if this is a known bug, or if it's even fixable ( Is this a unattended consequence from the  `display over other apps` permission?) but reporting here as I don't see this discussed anywhere else.

Example:

![image](https://user-images.githubusercontent.com/9147294/72118292-c7ebe480-33a4-11ea-9721-dd0bb6b35180.png)

**Comment by zacharee** [comment]
This isn't fixable.
