### ISSUE TITLE
500 MB+ of user Data?

### ISSUE THREAD

**Issue by bengalih** [zacharee/NachoNotch#15]
I have done several backup and restores of my Pixel 3 XL recently while I have been migrating to Android 11.
I have noticed that my backup programs have been hanging on backing up NachoNotch and upon investigating I have discovered that the app contained more than 500 MB of user data.

I'm not sure if the sheer size of this is causing backup issues, as I do have other apps with more data that back up properly.  As I have no idea what this data consists of it is possible there are thousands of small files that take an indeterminable time to backup.  I have let the backup run for over 30 minutes trying to backup this app and eventually have to kill it and then purge the user data.

I should mention that while I have used the app in the past, it has been reinstalled from scratch on my phone without ever being used and apparently still generates over 500 MB of user data.

I can't determine why an app that provides this function needs to generate such large amounts of user data.

Can a description of this excessive user data be provided?

**Comment by zacharee** [comment]
I have no idea where that data would be coming from.

Can you install this APK over the release version (remove the .zip extension)? It will set the app's data to be world-readable, so you'll be able to use ADB to browse to `/data/data/com.xda.nachonotch/` and see what's taking up so much space.

Tell me what you find.
[app-release.apk.zip](https://github.com/zacharee/NachoNotch/files/6071026/app-release.apk.zip)

**Comment by bengalih** [comment]
Thanks.  I needed to purge that data in order for my backup to complete - and I am reloading my phone from scratch now.
I'm 95% sure that this is the second time this occurred though - as I recall seeing this large amount of data several months ago when I was backing up.  I thought about posting here at that time, but I guess I lost track.

I will keep my eye on it over the next few weeks and see if it grows.  Again - I haven't actually been using the app, but have reinstalled it with every build so I would have it available if I wanted it.  I'm not sure I even launched the apk since last time.

Thanks for the response and I'll let you know what I find.

**Comment by bengalih** [comment]
Also...just to prove I'm not crazy:


<img src="https://user-images.githubusercontent.com/1746583/109700413-526a4700-7b57-11eb-9658-1c5df32c4397.png" alt="screenshot" width="250"/>
