### ISSUE TITLE
Black bar in full screen

### ISSUE THREAD

**Issue by tdemin** [zacharee/NachoNotch#2]
With the new version of Nacho Notch, the black bar is now shown at the top of the screen (if viewed in portrait mode) in full screen apps and there is no way to hide it. Please add an option to restore the original behavior.

**Comment by zacharee** [comment]
The immersive behavior wasn't changed.


On Sep 1, 2018 10:26 AM, Timur Demin <notifications@github.com> wrote:

With the new version of Nacho Notch, the black bar is now shown on the top of the screen (if viewed in portrait mode) in full screen apps and there is no way to hide it. Please add an option to restore the original behavior.

**Comment by tdemin** [comment]
These are the screenshots with two different NachoNotch versions. The black bar seems to only appear in portrait mode; it disappears in landscape mode apps (except for the camera app though).

[Camera, prev. NachoNotch version](https://user-images.githubusercontent.com/26599554/44986626-dbf82880-af9d-11e8-89c9-ec1337493dae.png)
[Gallery, prev. version](https://user-images.githubusercontent.com/26599554/44986627-dbf82880-af9d-11e8-9db2-555bd86d2fff.png)
[Gallery, new version](https://user-images.githubusercontent.com/26599554/44986628-dbf82880-af9d-11e8-81e5-7fb874ddc631.png)
[Camera, new version](https://user-images.githubusercontent.com/26599554/44986629-dc90bf00-af9d-11e8-84fe-bfe87c275dd0.png)

**Comment by swiftSwathSee** [comment]
Looks like last month's e4a4169 may be the beginning of a fix for this. Glad to see it, since this app is currently the only way to get black status & nav bars in Pie without root.

**Comment by swiftSwathSee** [comment]
@zacharee until a proper fix is released, an app blacklist option would be highly appreciated. It's very tedious having to manually disable Nacho Notch in every fullscreen portrait app.

The list would be user-specified and even if it lacked a proper GUI, it would still be much better than the current situation.

**Comment by zacharee** [comment]
A blacklist isn't feasible. It would require an accessibility service to always be running, and wouldn't be reliable.

Sent from Nine
________________________________

**Comment by swiftSwathSee** [comment]
I think this may have been fixed. @tdemin, can you verify on your end?
