### ISSUE TITLE
Bottom black bar doesn't recover from landscape sometimes 

### ISSUE THREAD

**Issue by AkazaRenn** [zacharee/NachoNotch#20]
When recovering from landscape mode, sometimes the bottom black bar doesn't appear. Switching landscape mode and switching back to portrait sometimes fixes it, sometimes it doesn't.

https://github.com/zacharee/NachoNotch/assets/8340896/f3dd2ed1-cbc6-44de-88be-b86a1dd78ac1

Once it happens, toggling either the app itself or the option for black nav bar doesn't fix that. It has to be done by flipping the phone like in the recording.

**Comment by AkazaRenn** [comment]
Hi @zacharee, thank you for updating the app. I was testing the latest release but feel like this issue is not fixed, can you please confirm? Thank you!

https://github.com/zacharee/NachoNotch/assets/8340896/53a8e58a-5af3-43eb-8f01-5e049dfa6f0a

**Comment by zacharee** [comment]
This should be fixed in version 38.

**Comment by AkazaRenn** [comment]
@zacharee it works like a charm, thank you!
