### ISSUE TITLE
Conflicts with fullscreen apps.

### ISSUE THREAD

**Issue by CC007** [zacharee/NachoNotch#21]
In fullscreen apps like WebToon the status bar obscures part of the page content.

I'm not talking about the rounded corners. Those do indeed obscure (by design) and are configurable. That's not the issue

The issue is that some full screen apps (like WebToon) get partially covered by the status bar. This makes text near the top of the page (like the text bubbles in comics) unreadable.

![Screenshot_20240202-001026](https://github.com/zacharee/NachoNotch/assets/5381337/0f55f7c7-0fe7-453e-8af7-b3491b98c83e)
![Screenshot_20240202-001014](https://github.com/zacharee/NachoNotch/assets/5381337/86b7de72-1eec-4ecf-a5a0-c19aeea21d4d)

These images are scrolled all the way to the top. The first one I would be okay with covering part of the page (that's by WebToon design), but in the second one, the comic should be fully visible.

**Comment by zacharee** [comment]
This should be fixed in the next version.
