### ISSUE TITLE
Notch is not visible on the lockscreen 

### ISSUE THREAD

**Issue by mr-d3falt** [zacharee/NachoNotch#23]
The notch does not display on the lockscreen .

**Comment by mr-d3falt** [comment]
I have read the FAQ and have seen the answer regarding the issue , I just wonder how the competing apps made it work ?
This may require additional permission which could be masked as accessibility application.

**Comment by mr-d3falt** [comment]
One workaround for users could be just adding the notch using the photoshop to the lockscreen wallpapers

**Comment by zacharee** [comment]
Accessibility overlays show above all system layers, including the status bar. Blacking it out would cover the status bar entirely.
