### ISSUE TITLE
Doesn't work on tablets in landscapes, although it could.

### ISSUE THREAD

**Issue by HTImen** [zacharee/NachoNotch#25]
![Screenshot_2024-06-13-11-23-40-407_com xda nachonotch](https://github.com/zacharee/NachoNotch/assets/126826249/cc8e88e9-9ce5-4785-8c90-c608c1e4e32e)
![Screenshot_2024-06-13-11-23-33-701_com xda nachonotch](https://github.com/zacharee/NachoNotch/assets/126826249/9a5ef758-d420-452e-a800-44cbc9376754)

**Comment by zacharee** [comment]
This is solved for devices with cutouts on the top in horizontal orientations in version 37.
