### ISSUE TITLE
Black status bar in immersive mode

### ISSUE THREAD

**Issue by AkazaRenn** [zacharee/NachoNotch#26]
![Screenshot_20240808_181523_Gallery.png](https://github.com/user-attachments/assets/c4fde843-ae2e-459f-b9b1-8dd3eb9e7139)

It only happens on status bar, bottom bar is ok.

**Comment by hendricha** [comment]
It is happening for me too. Downgraded to ver 38, apprently ver 39 is the version that broke it. Android version is sadly 11.

**Comment by hendricha** [comment]
Yesterday's update seems to have fixed it at first glance

**Comment by AkazaRenn** [comment]
I'm still experiencing it in her 41, will there be a new version with the fix soon?
