### ISSUE TITLE
Custom rounded corners radius

### ISSUE THREAD

**Issue by tdemin** [zacharee/NachoNotch#3]
Please add an option to set custom radius for rounded corners. Thanks in advance.

**Comment by andruwik777** [comment]
+1
Btw, is there some way not to cut full screen image/video with nanoNotch (but rather automatically ajust picture/video to new screen ratio) during notch hiding?

**Comment by zacharee** [comment]
No


Sent from Workspace ONE Boxer


On Oct 22, 2018 7:10 AM, andruwik777 <notifications@github.com> wrote:

+1
Btw, is there some way not to cut full screen image/video with nanoNotch (but rather automatically ajust picture/video to new screen ratio) during notch hiding?

**Comment by zacharee** [comment]
https://github.com/zacharee/NachoNotch/commit/1b5deadfbf16d6c10d27fe0fb54588354278d914
