### ISSUE TITLE
The app interferes with the navigation bar?

### ISSUE THREAD

**Issue by Tom4tot** [zacharee/NachoNotch#7]
When I activate your app with the quick setting, everything works fine except when I use an app with a light background, my navigation bar becomes white and the buttons disappear weirdly. Do you have any idea what's the issue?

Device: OnePlus 6
ROM: LOS 16 unofficial
Kernel: Blu Spark KERNEL
![screenshot_20181113-152441_kiwi_browser](https://user-images.githubusercontent.com/32274750/48391577-5510ba80-e75b-11e8-8671-fdc5cb7fa715.png)

Screenshot:

**Comment by zacharee** [comment]
This is explained in the terms you were supposed to read.

https://github.com/zacharee/NachoNotch/blob/master/app/src/main/assets/Terms.md

**Comment by erickrawczyk** [comment]
@zacharee is there anything that can be done to mitigate this? The terms don't really explain why this behavior happens and I don't know enough about android to investigate - is it a limitation of the overlay api or something?  It's the only bug/behavior that really frustrates me with this app
