### ISSUE TITLE
Stopped working on Pixel 3 XL - December 2018 security update

### ISSUE THREAD

**Issue by FlyOnTheWall43** [zacharee/NachoNotch#8]
This stopped working after I updated my Pixel 3 XL to PQ1A.181205.006.

**Comment by FlyOnTheWall43** [comment]
Ok, so maybe the update just toggled the quick setting? I am positive I had it on when I initiated the update, but i just checked and the reason it wasn't working is because it was toggled off. I turned it back on and it started working again.

**Comment by andraz** [comment]
Toggling works but it doesn't work on bootup.

I have found a bug with blacking-out the bar at the bottom when rotated.
https://www.reddit.com/r/GooglePixel/comments/acg98s/rotated_chrome_bug_on_pixel_3_xl/
